[2013-04-05 18:50:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1320
Stack trace:
#0 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(992): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(956): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-04-05 18:51:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1330
Stack trace:
#0 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(992): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(956): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-04-05 18:51:15] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '', Array)
#1 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(25): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(87): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1810): Illuminate\Database\DatabaseManager->connection(NULL)
#6 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1778): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#7 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1077): Illuminate\Database\Eloquent\Model->getConnection()
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1060): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(337): Illuminate\Database\Eloquent\Model->newQuery()
#10 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(12): Illuminate\Database\Eloquent\Model::all()
#11 [internal function]: TasklistsController->index()
#12 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#13 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array)
#14 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array)
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#17 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#18 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
[2013-04-05 21:55:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1330
Stack trace:
#0 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(992): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(956): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-04-05 22:02:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\HttpException' with message 'List was not updated' in /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:621
Stack trace:
#0 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(169): Illuminate\Foundation\Application->abort(500, 'List was not up...')
#1 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(85): Illuminate\Support\Facades\Facade::__callStatic('abort', Array)
#2 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(85): Illuminate\Support\Facades\App::abort(500, 'List was not up...')
#3 [internal function]: TasklistsController->update('10')
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#6 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('10')
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#10 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2013-04-05 22:05:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '$validation' (T_VARIABLE), expecting '(' in /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php line 85' in /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php:85
Stack trace:
#0 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Exception/ExceptionServiceProvider.php(113): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-05 22:05:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Compile Error: Cannot use [] for reading in /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php line 85' in /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php:85
Stack trace:
#0 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Exception/ExceptionServiceProvider.php(113): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-05 22:29:04] log.ERROR: exception 'Illuminate\Database\Eloquent\MassAssignmentException' with message 'name' in /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:253
Stack trace:
#0 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(87): Illuminate\Database\Eloquent\Model->fill(Array)
#1 [internal function]: TasklistsController->update('10')
#2 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('10')
#6 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#7 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-05 22:29:27] log.ERROR: exception 'Illuminate\Database\Eloquent\MassAssignmentException' with message 'name' in /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:253
Stack trace:
#0 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(87): Illuminate\Database\Eloquent\Model->fill(Array)
#1 [internal function]: TasklistsController->update('10')
#2 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('10')
#6 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#7 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-05 22:30:44] log.ERROR: exception 'ErrorException' with message 'Warning: Attempt to assign property of non-object in /Library/WebServer/Documents/hotspot/app/models/TaskList.php line 43' in /Library/WebServer/Documents/hotspot/app/models/TaskList.php:43
Stack trace:
#0 /Library/WebServer/Documents/hotspot/app/models/TaskList.php(43): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'Attempt to assi...', '/Library/WebSer...', 43, Array)
#1 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(87): TaskList::updateTask('10')
#2 [internal function]: TasklistsController->update('10')
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#5 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('10')
#7 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-04-05 22:31:34] log.ERROR: exception 'ErrorException' with message 'Warning: Attempt to assign property of non-object in /Library/WebServer/Documents/hotspot/app/models/TaskList.php line 43' in /Library/WebServer/Documents/hotspot/app/models/TaskList.php:43
Stack trace:
#0 /Library/WebServer/Documents/hotspot/app/models/TaskList.php(43): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'Attempt to assi...', '/Library/WebSer...', 43, Array)
#1 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(87): TaskList::updateTask('10')
#2 [internal function]: TasklistsController->update('10')
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#5 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('10')
#7 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-04-05 22:31:47] log.ERROR: exception 'ErrorException' with message 'Warning: Attempt to assign property of non-object in /Library/WebServer/Documents/hotspot/app/models/TaskList.php line 43' in /Library/WebServer/Documents/hotspot/app/models/TaskList.php:43
Stack trace:
#0 /Library/WebServer/Documents/hotspot/app/models/TaskList.php(43): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'Attempt to assi...', '/Library/WebSer...', 43, Array)
#1 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(87): TaskList::updateTask('10')
#2 [internal function]: TasklistsController->update('10')
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#5 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('10')
#7 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-04-05 22:31:58] log.ERROR: exception 'ErrorException' with message 'Warning: Attempt to assign property of non-object in /Library/WebServer/Documents/hotspot/app/models/TaskList.php line 43' in /Library/WebServer/Documents/hotspot/app/models/TaskList.php:43
Stack trace:
#0 /Library/WebServer/Documents/hotspot/app/models/TaskList.php(43): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'Attempt to assi...', '/Library/WebSer...', 43, Array)
#1 /Library/WebServer/Documents/hotspot/app/controllers/TasklistsController.php(87): TaskList::updateTask('10')
#2 [internal function]: TasklistsController->update('10')
#3 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#5 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('10')
#7 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#8 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#9 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(476): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Library/WebServer/Documents/hotspot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(461): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Library/WebServer/Documents/hotspot/public/index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
